/*
 * 提出書類AIアシスタント（モック）
 * ダミーデータ定義
 * すべて架空の会社・人物です。実在の団体とは関係ありません。
 */

const SEED_DATA = {
  meta: {
    productName: "提出書類AIアシスタント",
    planName: "スタンダードプラン",
    planPrice: 4980,
    userName: "田中 事務員",
  },

  company: {
    name: "株式会社三和設備",
    representative: "三和 康弘",
    postal: "130-0021",
    address: "東京都墨田区緑1-2-3 三和ビル3F",
    phone: "03-1234-5678",
    licenseNumber: "東京都知事許可（般-4）第123456号",
    licenseTypes: ["電気工事業", "管工事業"],
    licenseExpiry: "2026-09-10",
    insurance: {
      rousai: "加入済（労災保険番号：1301-xxxxxx-x）",
      kenkohoken: "全国健康保険協会 東京支部",
      kosei: "加入済",
      koyo: "加入済",
    },
    // 会社として提出に使う共通書類（サイト横断で使い回す）
    documents: [
      { id: "cd1", name: "建設業許可証", fulfilled: true, updatedAt: "2026-06-01" },
      { id: "cd2", name: "社会保険関係資料", fulfilled: true, updatedAt: "2026-06-01" },
      { id: "cd3", name: "労災保険資料", fulfilled: false, updatedAt: null },
      { id: "cd4", name: "会社概要資料", fulfilled: true, updatedAt: "2026-05-10" },
    ],
  },

  clients: [
    { id: "c1", name: "ABC建設株式会社" },
    { id: "c2", name: "東都建設株式会社" },
    { id: "c3", name: "中央工務株式会社" },
  ],

  // 資格・講習の種類マスタ
  certTypes: [
    { id: "ct1", name: "玉掛け技能講習", hasExpiry: false },
    { id: "ct2", name: "高所作業車運転技能講習", hasExpiry: true },
    { id: "ct3", name: "フルハーネス型安全帯特別教育", hasExpiry: true },
    { id: "ct4", name: "職長・安全衛生責任者教育", hasExpiry: true },
    { id: "ct5", name: "足場の組立て等特別教育", hasExpiry: false },
    { id: "ct6", name: "アーク溶接特別教育", hasExpiry: false },
  ],

  workers: [
    {
      id: "w1",
      name: "山田 太郎",
      kana: "ヤマダ タロウ",
      birthdate: "1988-04-12",
      affiliation: "株式会社三和設備（本工）",
      jobType: "電気工事士",
      phone: "090-1111-2222",
      email: "yamada@example.com",
      avatarColor: "#2563eb",
      certs: [
        {
          id: "w1-ct1",
          certTypeId: "ct1",
          issuer: "東京技能講習センター",
          certNumber: "TAMA-118823",
          obtainedDate: "2022-04-01",
          expiryDate: null,
        },
        {
          id: "w1-ct3",
          certTypeId: "ct3",
          issuer: "関東安全衛生教育協会",
          certNumber: "FH-220456",
          obtainedDate: "2023-06-10",
          expiryDate: "2026-08-25",
        },
        {
          id: "w1-ct4",
          certTypeId: "ct4",
          issuer: "建設労務安全研究会",
          certNumber: "SH-330912",
          obtainedDate: "2023-09-10",
          expiryDate: "2026-09-10",
        },
      ],
    },
    {
      id: "w2",
      name: "鈴木 一郎",
      kana: "スズキ イチロウ",
      birthdate: "1990-11-02",
      affiliation: "株式会社三和設備（本工）",
      jobType: "配管工",
      phone: "090-2222-3333",
      email: "suzuki@example.com",
      avatarColor: "#059669",
      certs: [
        {
          id: "w2-ct1",
          certTypeId: "ct1",
          issuer: "東京技能講習センター",
          certNumber: "TAMA-098211",
          obtainedDate: "2021-05-12",
          expiryDate: null,
        },
        {
          id: "w2-ct2",
          certTypeId: "ct2",
          issuer: "全国高所作業車協会",
          certNumber: "KOSHO-55231",
          obtainedDate: "2024-01-10",
          expiryDate: "2026-09-05",
        },
      ],
    },
    {
      id: "w3",
      name: "佐藤 健",
      kana: "サトウ ケン",
      birthdate: "1985-02-20",
      affiliation: "株式会社三和設備（協力工）",
      jobType: "足場鳶",
      phone: "090-3333-4444",
      email: "sato@example.com",
      avatarColor: "#d97706",
      certs: [
        {
          id: "w3-ct5",
          certTypeId: "ct5",
          issuer: "関東足場技能協会",
          certNumber: "ASHIBA-77120",
          obtainedDate: "2020-03-01",
          expiryDate: null,
        },
        {
          id: "w3-ct3",
          certTypeId: "ct3",
          issuer: "関東安全衛生教育協会",
          certNumber: "FH-190233",
          obtainedDate: "2022-02-01",
          expiryDate: "2026-07-31",
        },
      ],
    },
    {
      id: "w4",
      name: "高橋 誠",
      kana: "タカハシ マコト",
      birthdate: "1979-07-08",
      affiliation: "株式会社三和設備（本工）",
      jobType: "電気工事士",
      phone: "090-4444-5555",
      email: "takahashi@example.com",
      avatarColor: "#7c3aed",
      certs: [
        {
          id: "w4-ct1",
          certTypeId: "ct1",
          issuer: "東京技能講習センター",
          certNumber: "TAMA-055120",
          obtainedDate: "2019-09-09",
          expiryDate: null,
        },
        {
          id: "w4-ct4",
          certTypeId: "ct4",
          issuer: "建設労務安全研究会",
          certNumber: "SH-101233",
          obtainedDate: "2020-05-01",
          expiryDate: "2026-06-01",
        },
        {
          id: "w4-ct2",
          certTypeId: "ct2",
          issuer: "全国高所作業車協会",
          certNumber: "KOSHO-40982",
          obtainedDate: "2023-09-15",
          expiryDate: "2026-09-15",
        },
      ],
    },
    {
      id: "w5",
      name: "伊藤 翔太",
      kana: "イトウ ショウタ",
      birthdate: "1999-01-15",
      affiliation: "株式会社三和設備（本工）",
      jobType: "設備工",
      phone: "090-5555-6666",
      email: "ito@example.com",
      avatarColor: "#db2777",
      certs: [
        {
          id: "w5-ct2",
          certTypeId: "ct2",
          issuer: "全国高所作業車協会",
          certNumber: "KOSHO-66710",
          obtainedDate: "2023-08-01",
          expiryDate: "2026-08-20",
        },
        {
          id: "w5-ct6",
          certTypeId: "ct6",
          issuer: "日本溶接技術振興会",
          certNumber: "ARC-30045",
          obtainedDate: "2024-02-01",
          expiryDate: null,
        },
      ],
    },
  ],

  sites: [
    {
      id: "s1",
      name: "○○ビル新築工事",
      clientId: "c1",
      periodStart: "2026-07-01",
      periodEnd: "2026-10-31",
      deadline: "2026-08-25",
      status: "準備中",
      plannedWorkerIds: ["w1", "w2", "w3", "w4", "w5"],
      requiredCompanyDocIds: ["cd1", "cd2", "cd3"],
      workerRequirements: [
        { workerId: "w1", certTypeId: "ct1" },
        { workerId: "w1", certTypeId: "ct2" },
        { workerId: "w2", certTypeId: "ct1" },
        { workerId: "w2", certTypeId: "ct2" },
        { workerId: "w3", certTypeId: "ct5" },
        { workerId: "w4", certTypeId: "ct1" },
        { workerId: "w5", certTypeId: "ct2" },
      ],
      submissionGenerated: false,
      submissionGeneratedAt: null,
    },
    {
      id: "s2",
      name: "新宿オフィス改修工事",
      clientId: "c2",
      periodStart: "2026-08-01",
      periodEnd: "2026-09-30",
      deadline: "2026-09-05",
      status: "準備中",
      plannedWorkerIds: ["w2", "w3", "w4"],
      requiredCompanyDocIds: ["cd1", "cd2"],
      workerRequirements: [
        { workerId: "w2", certTypeId: "ct1" },
        { workerId: "w2", certTypeId: "ct2" },
        { workerId: "w3", certTypeId: "ct5" },
        { workerId: "w3", certTypeId: "ct3" },
        { workerId: "w4", certTypeId: "ct1" },
        { workerId: "w4", certTypeId: "ct2" },
        { workerId: "w4", certTypeId: "ct4" },
      ],
      submissionGenerated: false,
      submissionGeneratedAt: null,
    },
    {
      id: "s3",
      name: "世田谷マンション設備工事",
      clientId: "c3",
      periodStart: "2026-08-10",
      periodEnd: "2026-11-20",
      deadline: "2026-09-15",
      status: "準備中",
      plannedWorkerIds: ["w1", "w5"],
      requiredCompanyDocIds: ["cd1", "cd2", "cd3", "cd4"],
      workerRequirements: [
        { workerId: "w1", certTypeId: "ct1" },
        { workerId: "w1", certTypeId: "ct3" },
        { workerId: "w5", certTypeId: "ct2" },
        { workerId: "w5", certTypeId: "ct3" },
      ],
      submissionGenerated: false,
      submissionGeneratedAt: null,
    },
    {
      id: "s4",
      name: "品川倉庫改修工事",
      clientId: "c1",
      periodStart: "2026-05-01",
      periodEnd: "2026-07-20",
      deadline: "2026-07-20",
      status: "提出済",
      plannedWorkerIds: ["w2", "w4"],
      requiredCompanyDocIds: ["cd1", "cd2"],
      workerRequirements: [
        { workerId: "w2", certTypeId: "ct1" },
        { workerId: "w4", certTypeId: "ct1" },
      ],
      submissionGenerated: true,
      submissionGeneratedAt: "2026-07-15T10:30:00",
    },
    {
      id: "s5",
      name: "横浜工場設備更新工事",
      clientId: "c2",
      periodStart: "2026-09-01",
      periodEnd: "2026-12-15",
      deadline: "2026-10-01",
      status: "未着手",
      plannedWorkerIds: ["w3", "w5"],
      requiredCompanyDocIds: ["cd1", "cd2", "cd3"],
      workerRequirements: [
        { workerId: "w3", certTypeId: "ct2" },
        { workerId: "w5", certTypeId: "ct3" },
        { workerId: "w5", certTypeId: "ct6" },
      ],
      submissionGenerated: false,
      submissionGeneratedAt: null,
    },
  ],

  // 不足資料の依頼履歴（送信すると追加される）
  requests: [],
};

// ディープコピーして返す（seedを汚染しない）
function cloneSeedData() {
  return JSON.parse(JSON.stringify(SEED_DATA));
}
